# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c50d74e8758b15ee70372cd5556d34d6fe65c6746e71f5e36eab19a67f3be22b676bc9521e687f05614d9d5ac36f0f55ab2040dca16941d2fbfa75010257e400

test:
  secret_key_base: f63f7c390768b8522db9cc7c23ecee028c55100b261d7606c08a651ba75fef5768924712fdf2b180ba6556afa90c4b1cf34b649602a985c16ec2a240bc26cbb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
